name: RetroArch Windows Stable Build

on:
  create:
    tags:
      - v*

jobs:
  job1:
    name: Build RetroArch AppImage
    runs-on: windows-latest

    steps:
    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.get_tag_name.outputs.VERSION }}
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: Fetch dependencies
      run: |
        msys2do pacman --noconfirm -Su
        msys2do pacman -S --noconfirm --needed wget git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-ntldd mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libxml2 mingw-w64-x86_64-freetype mingw-w64-x86_64-python3 mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-drmingw mingw-w64-x86_64-qt5  mingw-w64-x86_64-openssl p7zip
        msys2do wget https://sourceforge.net/projects/mingw-w64-archlinux/files/x86_64/mingw-w64-nvidia-cg-toolkit-3.1-2-any_4.pkg.tar.xz/download -O mingw-w64-x86_64-nvidia-cg-toolkit-3.1-2-any.pkg.tar.xz && pacman -U mingw-w64-x86_64-nvidia-cg-toolkit-3.1-2-any.pkg.tar.xz
    - name: Build RetroArch
      run: |
        msys2do ./configure
        msys2do make -j8
    - name: Package libs
      run: for i in $(seq 3); do for bin in $(ntldd -R *exe | grep -i mingw | cut -d">" -f2 | cut -d" " -f2); do cp -vu "$bin" . ; done; done
    - name: Zip the libs
      run: 7z a redist_libs-${{ steps.get_tag_name.outputs.VERSION }}.7z *.dll
    - name: Zip it up!
      run: 7z a RetroArch-Win-x86_64_${{ steps.get_tag_name.outputs.VERSION }}.7z *.exe *.dll
    - name: Upload RetroArch release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RetroArch-Win-x86_64_${{ steps.get_tag_name.outputs.VERSION }}.7z
        tag: ${{ steps.get_tag_name.outputs.VERSION }}
        asset_name: RetroArch-Win-x86_64_${{ steps.get_tag_name.outputs.VERSION }}.7z
        overwrite: true
    - name: Upload redist libs
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: redist_libs-${{ steps.get_tag_name.outputs.VERSION }}.7z
        tag: ${{ steps.get_tag_name.outputs.VERSION }}
        asset_name: redist_libs-${{ steps.get_tag_name.outputs.VERSION }}.7z
        overwrite: true
