name: RetroArch Windows Stable Build

on:
  create:
    tags:
      - v*

jobs:
  job1:
    name: Build RetroArch AppImage
    runs-on: windows-latest

    steps:
    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.get_tag_name.outputs.VERSION }}
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: Fetch dependencies
      run: |
        msys2do pacman --noconfirm -Su
        msys2do pacman -S --noconfirm --needed wget git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-ntldd mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libxml2 mingw-w64-x86_64-freetype mingw-w64-x86_64-python3 mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-drmingw p7zip
    - name: Build RetroArch
      run: |
        msys2do ./configure --disable-ffmpeg --disable-vulkan --disable-spirv_cross --disable-builtinglslang
        msys2do make -j8
    - name: Create working directory
      run: msys2do mkdir working_dir
    - name: Make asset dirs
      working-directory: working_dir
      run: |
        msys2do mkdir assets
        msys2do mkdir cores
        msys2do mkdir shaders
        msys2do mkdir database
        msys2do mkdir cheats
#    - name: Fetch assets
#      working-directory: working_dir/assets
#      run: |
#        msys2do wget https://buildbot.libretro.com/assets/frontend/assets.zip
#        msys2do unzip assets.zip
#        msys2do rm assets.zip
    - name: Fetch overlays
      working-directory: working_dir
      run: |
        msys2do git clone https://github.com/libretro/common-overlays.git
        msys2do mv common-overlays overlays
    - name: Fetch autoconfigs
      working-directory: working_dir
      run: |
        msys2do git clone https://github.com/libretro/retroarch-joypad-autoconfig.git
        msys2do mv retroarch-joypad-autoconfig autoconfig
    - name: Fetch shaders
      working-directory: working_dir/shaders
      run: |
        msys2do git clone https://github.com/libretro/glsl-shaders.git
        msys2do mv glsl-shaders shaders_glsl
        msys2do git clone https://github.com/libretro/slang-shaders.git
        msys2do mv slang-shaders shaders_slang
        msys2do git clone https://github.com/libretro/common-shaders.git
        msys2do mv common-shaders shaders_cg
#    - name: Fetch databases
#      working-directory: working_dir/database
#      run: |
#        msys2do wget https://buildbot.libretro.com/assets/frontend/database-rdb.zip
#        msys2do unzip database-rdb.zip
#        msys2do rm database-rdb.zip
#    - name: Fetch cheats
#      working-directory: working_dir/cheats
#      run: |
#        msys2do wget https://buildbot.libretro.com/assets/frontend/cheats.zip
#        msys2do unzip cheats.zip
#        msys2do rm cheats.zip
#    - name: Fetch core info
#      working-directory: working_dir/cores
#      run: |
#        msys2do wget https://buildbot.libretro.com/assets/frontend/info.zip
#        msys2do unzip info.zip
#        msys2do rm info.zip
    - name: Gather the libs
      run: ForEach ($l in $(msys2do ntldd.exe -R '*.exe'|grep mingw64|sed -e 's/^[ \t]*//'|cut -d' ' -f3)){cp "$l" ./working_dir}
    - name: Zip just the libs
      working-directory: working_dir/cores
      run: 7z a redist_libs-${{ steps.get_tag_name.outputs.VERSION }}.7z *.dll
    - name: Move executables and libs to working dir
      run: mv *.exe working_dir
    - name: Zip the full release
      working-directory: working_dir
      run: 7z a RetroArch-Win-x86_64_${{ steps.get_tag_name.outputs.VERSION }}.7z *
    - name: Upload RetroArch release bundle
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: working_dir/RetroArch-Win-x86_64_${{ steps.get_tag_name.outputs.VERSION }}.7z
        tag: ${{ steps.get_tag_name.outputs.VERSION }}
        asset_name: RetroArch-Win-x86_64_${{ steps.get_tag_name.outputs.VERSION }}.7z
        overwrite: true
    - name: Upload redist libs
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: redist_libs-${{ steps.get_tag_name.outputs.VERSION }}.7z
        tag: ${{ steps.get_tag_name.outputs.VERSION }}
        asset_name: redist_libs-${{ steps.get_tag_name.outputs.VERSION }}.7z
        overwrite: true
